### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by matak07** [davidnvq/me_recognition#1]
Hi @quanguet 
I tried to run the code in file train_me_loso_baseline.py, however, I keep on getting the following error. When I tried to debug, I found that the value for variable 'aux' in /capsule/data/dataset.py is not changing and remain 'None'. Can you please help me resolve this error?

/usr/bin/python3.5 /../../../../codes/me_recognition-master/train_me_loso_baseline.py
subject_out smic_20
df_neg (377, 11)
df_pos (371, 11)
df_sur (373, 11)
/usr/local/lib/python3.5/dist-packages/torch/optim/lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
  0%|          | 0/36 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/../../../../codes/me_recognition-master/train_me_loso_baseline.py", line 224, in <module>
    scores = train_eval(subject_out_idx=i)
  File "/../../../../codes/me_recognition-master/train_me_loso_baseline.py", line 206, in train_eval
    epoch)
  File "/../../../../codes/me_recognition-master/train_me_loso_baseline.py", line 125, in on_epoch
    for i, (x, y) in enumerate(train_loader):  # batch training
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/../../../../codes/me_recognition-master/capsule/data/dataset.py", line 47, in __getitem__
    return img, label, self.aux[idx]
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by guman90203** [comment]
Hi, I'm curious that whether you solve this problem cause I'm facing the same problem too

**Comment by matak07** [comment]
@guman90203 No, I could not get it resolved, neither is there any reply from the author.

**Comment by guman90203** [comment]
@matak07  Hi, sorry to hear about that, did you ever find out what aux in the dataset.py mean?
I read this paper but I still couldn't fin out what is this aux mean?

**Comment by davidnvq** [comment]
I'm sorry for late reply since I have been unaware of the notification :'(. Are you still get the problem @guman90203?

**Comment by guman90203** [comment]
@davidnvq  It's ok, I realized that it might be the parameters you use to debug so I just delete it and it work just fine. Thanks for the reply though~

**Comment by davidnvq** [comment]
Thanks. I just realized my Github notification setting is off. I haven't worked on this topic anymore but if you have any concerns, feel free to ask. I may try to help if possible.
